#!/usr/bin/env python3
"""CodeReviewerBot 文档稳定性测试

Generates documentation 5 times using the doc-generation Agent, then uses
the LLM to compare outputs for similarity (target: ≥85%).

Usage:
    python scripts/test_docs_stability.py

    # Skip generation (use existing test data)
    python scripts/test_docs_stability.py --skip-gen

    # Custom output directory and runs
    python scripts/test_docs_stability.py --output-dir /tmp/stability_test --runs 5
"""

from __future__ import annotations

import difflib
import json
import os
import shutil
import sys
import tempfile
import time
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
_SRC = _PROJECT_ROOT / "src"
sys.path.insert(0, str(_SRC))

from crb.config.settings import LLMConfig
from crb.llm.client import LLMError, chat

# Default settings
DEFAULT_RUNS = 5
SIMILARITY_THRESHOLD = 0.85

# Docs that should be generated (relative to test output dir)
DOC_PATHS = [
    "docs/structure.md",
    "docs/config/structure.md",
    "docs/report/structure.md",
    "docs/llm/structure.md",
    "docs/cli/structure.md",
    "docs/analyzers/generic/structure.md",
    "docs/analyzers/python/structure.md",
    "docs/analyzers/c_cpp/structure.md",
    "docs/analyzers/go/structure.md",
    "docs/analyzers/rust/structure.md",
]


def run_generation(
    llm_config: LLMConfig,
    output_dir: Path,
    run_id: int,
    verbose: bool = True,
) -> int:
    """Run docs_gen_agent.py once, saving output to output_dir/run_{run_id}/."""
    run_dir = output_dir / f"run_{run_id}"
    run_dir.mkdir(parents=True, exist_ok=True)

    if verbose:
        print(f"  Run {run_id}: generating to {run_dir}")

    import subprocess
    agent_script = str(_SCRIPT_DIR / "docs_gen_agent.py")

    env = os.environ.copy()
    result = subprocess.run(
        [sys.executable, agent_script, "--all", "--output-dir", str(run_dir)],
        capture_output=True,
        text=True,
        env=env,
    )

    if verbose:
        for line in result.stdout.strip().split("\n"):
            if line.strip():
                print(f"    {line}")
        if result.stderr.strip():
            print(f"    [stderr] {result.stderr.strip()[:200]}")

    # Count generated docs
    count = 0
    for doc_rel in DOC_PATHS:
        doc_path = run_dir / doc_rel
        if doc_path.exists():
            count += 1

    return result.returncode, count


def _strip_frontmatter(content: str) -> str:
    """Strip Mermaid frontmatter markers and normalize whitespace."""
    lines = content.split("\n")
    cleaned = []
    for line in lines:
        # Normalize whitespace
        cleaned.append(line.strip())
    return "\n".join(cleaned)


def compute_pairwise_similarity(run1_dir: Path, run2_dir: Path) -> float:
    """Compute average difflib similarity across all docs between two runs."""
    scores = []
    for doc_rel in DOC_PATHS:
        f1 = run1_dir / doc_rel
        f2 = run2_dir / doc_rel
        if not f1.exists() or not f2.exists():
            continue
        t1 = _strip_frontmatter(f1.read_text(encoding="utf-8"))
        t2 = _strip_frontmatter(f2.read_text(encoding="utf-8"))
        ratio = difflib.SequenceMatcher(None, t1, t2).ratio()
        scores.append(ratio)

    if not scores:
        return 0.0
    return sum(scores) / len(scores)


def build_comparison_prompt(runs_dir: Path, run_ids: list[int]) -> str:
    """Build a prompt comparing docs across all runs."""
    parts = [
        "Compare the following 5 sets of documentation generated by an AI doc-gen agent.",
        "Each set (run_1 through run_5) contains the same 10 markdown files for the same project.",
        "Rate the OVERALL SIMILARITY across all 5 runs on a scale of 0-100%.",
        "",
        "Criteria for similarity:",
        "- Same structure/layout (uses same headings, same Mermaid graph structure)",
        "- Same cross-references between files",
        "- Consistent descriptions (minor word choice differences are OK)",
        "- Same Mermaid node names and relationships (minor formatting is OK)",
        "",
        "The content doesn't need to be identical - the structure, relationships, and key",
        "information should be consistent. 85% means: a human reader would recognize these",
        "as describing the same codebase with only minor variations in phrasing.",
        "",
        "Output ONLY a JSON object with this format:",
        '{  "overall_similarity": <0.0-1.0>,',
        '  "meets_threshold": <true/false>,',
        '  "min_similarity": <0.0-1.0>,',
        '  "max_similarity": <0.0-1.0>,',
        '  "assessment": "<brief explanation>"',
        "}",
        "",
    ]

    for rid in run_ids:
        run_dir = runs_dir / f"run_{rid}"
        parts.append(f"\n{'='*60}")
        parts.append(f"RUN {rid}")
        parts.append(f"{'='*60}\n")

        for doc_rel in DOC_PATHS:
            doc_path = run_dir / doc_rel
            if doc_path.exists():
                content = doc_path.read_text(encoding="utf-8")
                # Truncate very long docs
                if len(content) > 2000:
                    content = content[:2000] + "\n... [truncated]"
                parts.append(f"--- {doc_rel} ---")
                parts.append(content)
                parts.append("")

    return "\n".join(parts)


def llm_similarity_check(
    llm_config: LLMConfig,
    runs_dir: Path,
    run_ids: list[int],
    verbose: bool = True,
) -> dict | None:
    """Use the LLM to compare docs across runs for similarity."""
    prompt = build_comparison_prompt(runs_dir, run_ids)

    if verbose:
        print(f"  Comparing {len(run_ids)} runs via LLM...", end=" ", flush=True)

    system_prompt = (
        "You are a documentation quality evaluator. Compare documentation sets "
        "generated from the same source code and rate their similarity. "
        "Output ONLY valid JSON, no other text."
    )

    try:
        response = chat(
            config=llm_config,
            system_prompt=system_prompt,
            user_prompt=prompt,
            temperature=0.1,
        )
        # Extract JSON from response
        response = response.strip()
        # Try to find JSON in the response
        json_start = response.find("{")
        json_end = response.rfind("}")
        if json_start >= 0 and json_end > json_start:
            response = response[json_start:json_end + 1]

        result = json.loads(response)
        if verbose:
            sim = result.get("overall_similarity", 0)
            thresh = result.get("meets_threshold", False)
            print(f"{sim*100:.1f}% {'✓' if thresh else '✗'}")
        return result
    except (LLMError, json.JSONDecodeError) as e:
        if verbose:
            print(f"FAILED: {e}")
        return None


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="CodeReviewerBot Doc Stability Test")
    parser.add_argument("--output-dir", default=None, help="Test output directory (default: temp dir)")
    parser.add_argument("--runs", type=int, default=DEFAULT_RUNS, help=f"Number of generations (default: {DEFAULT_RUNS})")
    parser.add_argument("--skip-gen", action="store_true", help="Skip generation, use existing test data")
    parser.add_argument("--verbose", "-v", action="store_true", default=True, help="Verbose output")

    args = parser.parse_args()

    llm_config = LLMConfig.from_env()
    if not llm_config.is_valid():
        print("Error: LLM not configured.")
        sys.exit(1)

    # Setup test output directory
    if args.output_dir:
        test_base = Path(args.output_dir)
    else:
        test_base = _PROJECT_ROOT / "test_docs_stability"
    test_base = test_base.resolve()

    if not args.skip_gen:
        # Clean previous test data
        if test_base.exists():
            shutil.rmtree(test_base)

        print("=" * 60)
        print(f"CodeReviewerBot Doc Stability Test")
        print(f"Generating {args.runs} runs of documentation")
        print(f"Output: {test_base}")
        print(f"LLM: {llm_config.model or 'default'} @ {llm_config.api_url}")
        print("=" * 60)
        print()

        successes = 0
        total_docs = 0
        start_time = time.time()

        for i in range(1, args.runs + 1):
            rc, count = run_generation(llm_config, test_base, i, verbose=args.verbose)
            if rc == 0:
                successes += 1
            total_docs += count
            # Brief pause between runs
            if i < args.runs:
                time.sleep(1)

        elapsed = time.time() - start_time
        print()
        print(f"Generation complete: {successes}/{args.runs} runs succeeded, {total_docs} total docs")
        print(f"Time: {elapsed:.1f}s")
    else:
        if not test_base.exists():
            print(f"Error: {test_base} not found. Run without --skip-gen first.")
            sys.exit(1)
        # Count existing runs
        run_dirs = sorted(test_base.glob("run_*"))
        args.runs = len(run_dirs)
        print(f"Using {args.runs} existing runs from {test_base}")
        total_docs = sum(
            1 for r in run_dirs
            for doc_rel in DOC_PATHS
            if (r / doc_rel).exists()
        )

    print()

    # ── Similarity Analysis ──
    run_ids = list(range(1, args.runs + 1))

    print("─" * 60)
    print("Similarity Analysis")
    print("─" * 60)

    # Method 1: difflib pairwise comparison (fast baseline)
    print("\n[Text similarity (difflib)]")
    pairwise_scores = []
    for i in run_ids:
        for j in range(i + 1, args.runs + 1):
            sim = compute_pairwise_similarity(
                test_base / f"run_{i}",
                test_base / f"run_{j}",
            )
            pairwise_scores.append((i, j, sim))
            print(f"  Run {i} vs Run {j}: {sim*100:.1f}%")

    if pairwise_scores:
        avg_text_sim = sum(s for _, _, s in pairwise_scores) / len(pairwise_scores)
        min_text_sim = min(s for _, _, s in pairwise_scores)
        print(f"\n  Average text similarity: {avg_text_sim*100:.1f}%")
        print(f"  Minimum text similarity: {min_text_sim*100:.1f}%")

    # Method 2: LLM-based similarity assessment
    print("\n[LLM similarity assessment]")
    llm_result = llm_similarity_check(llm_config, test_base, run_ids, verbose=args.verbose)

    if llm_result:
        overall = llm_result.get("overall_similarity", 0)
        meets = llm_result.get("meets_threshold", False)
        assessment = llm_result.get("assessment", "")
        print(f"  Overall similarity: {overall*100:.1f}%")
        print(f"  Meets ≥85% threshold: {'YES ✓' if meets else 'NO ✗'}")
        if assessment:
            print(f"  Assessment: {assessment}")

        # Final verdict
        print()
        print("=" * 60)
        if meets:
            print("RESULT: PASS ✓ Documentation output is stable (≥85% similarity)")
        else:
            print("RESULT: FAIL ✗ Documentation output is unstable (<85% similarity)")
        print("=" * 60)
    else:
        print("\nLLM comparison failed. Using difflib results as fallback.")
        avg_sim = avg_text_sim if pairwise_scores else 0
        print(f"Average text similarity: {avg_sim*100:.1f}%")
        if avg_sim >= SIMILARITY_THRESHOLD:
            print(f"\nRESULT: PASS ✓ (text similarity ≥{SIMILARITY_THRESHOLD*100:.0f}%)")
        else:
            print(f"\nRESULT: FAIL ✗ (text similarity <{SIMILARITY_THRESHOLD*100:.0f}%)")

    # Summary report
    print()
    summary = {
        "total_runs": args.runs,
        "total_docs": total_docs,
        "avg_text_similarity": round(avg_text_sim * 100, 1) if pairwise_scores else None,
        "min_text_similarity": round(min_text_sim * 100, 1) if pairwise_scores else None,
        "llm_similarity": round(llm_result.get("overall_similarity", 0) * 100, 1) if llm_result else None,
        "llm_meets_threshold": llm_result.get("meets_threshold", False) if llm_result else None,
        "llm_assessment": llm_result.get("assessment", "") if llm_result else "",
    }

    summary_path = test_base / "stability_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Summary saved to {summary_path}")


if __name__ == "__main__":
    main()
