"""CI/CD template generator for target projects.

Generates CI/CD pipeline configs (GitHub Actions / GitLab CI / etc.)
based on detected project languages and frameworks.

Requirements: 2.6 CI/CD 门禁管理 — 模板生成
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional


def detect_project_languages(project_root: str) -> dict[str, bool]:
    """Auto-detect languages used in a project by scanning source files."""
    result: dict[str, bool] = {
        "python": False,
        "go": False,
        "rust": False,
        "c_cpp": False,
    }
    root = Path(project_root)
    for fp in root.rglob("*"):
        if fp.is_file() and not any(
            p.startswith(".") or p in ("node_modules", "venv", ".venv", "__pycache__", "build", "dist")
            for p in fp.relative_to(root).parts
        ):
            if fp.suffix == ".py":
                result["python"] = True
            elif fp.suffix == ".go":
                result["go"] = True
            elif fp.suffix in (".rs",):
                result["rust"] = True
            elif fp.suffix in (".c", ".h", ".cpp", ".hpp", ".cc", ".cxx"):
                result["c_cpp"] = True
    return result


def _filter_nonempty(lines: list[str]) -> str:
    return "\n".join(line for line in lines if line.strip()) + "\n"


def _list_python_lint_steps() -> list[str]:
    return [
        "      - name: Lint with ruff",
        '        run: ruff check src/',
        "      - name: Type check with mypy",
        "        run: mypy src/",
        "      - name: Format check",
        '        run: ruff format --check src/',
    ]


def _list_go_lint_steps() -> list[str]:
    return [
        "      - name: Lint with golangci-lint",
        "        run: golangci-lint run ./...",
        "      - name: Format check",
        "        run: gofmt -l .",
        "      - name: Vet",
        "        run: go vet ./...",
    ]


def _list_rust_lint_steps() -> list[str]:
    return [
        "      - name: Format check",
        "        run: cargo fmt --check",
        "      - name: Lint with clippy",
        "        run: cargo clippy -- -D warnings",
    ]


def _list_cpp_lint_steps() -> list[str]:
    return [
        "      - name: Lint with clang-tidy",
        "        run: clang-tidy src/ --checks='*' --warnings-as-errors='*'",
        "      - name: Format check",
        "        run: clang-format --dry-run --Werror src/",
    ]


def _list_python_test_steps() -> list[str]:
    return [
        "      - name: Install dependencies",
        "        run: pip install -e '.[dev]'",
        "      - name: Run tests",
        "        run: python -m pytest tests/ -v --cov=src --cov-report=term-missing",
    ]


def _list_go_test_steps() -> list[str]:
    return [
        "      - name: Run tests",
        "        run: go test ./... -v -race -coverprofile=coverage.out",
    ]


def _list_rust_test_steps() -> list[str]:
    return [
        "      - name: Run tests",
        "        run: cargo test --all-features",
    ]


def _list_cpp_test_steps() -> list[str]:
    return [
        "      - name: Configure",
        "        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug",
        "      - name: Build",
        "        run: cmake --build build",
        "      - name: Run tests",
        "        run: ctest --test-dir build --output-on-failure",
    ]


def generate_github_actions(
    project_root: str,
    languages: Optional[dict[str, bool]] = None,
) -> str:
    """Generate a GitHub Actions CI configuration for the detected project.

    Args:
        project_root: Project root directory.
        languages: Pre-detected languages (None = auto-detect).

    Returns:
        GitHub Actions YAML content.
    """
    if languages is None:
        languages = detect_project_languages(project_root)

    test_jobs: list[str] = []
    lint_jobs: list[str] = []

    if languages.get("python"):
        test_jobs.extend(_list_python_test_steps())
        lint_jobs.extend(_list_python_lint_steps())
    if languages.get("go"):
        test_jobs.extend(_list_go_test_steps())
        lint_jobs.extend(_list_go_lint_steps())
    if languages.get("rust"):
        test_jobs.extend(_list_rust_test_steps())
        lint_jobs.extend(_list_rust_lint_steps())
    if languages.get("c_cpp"):
        test_jobs.extend(_list_cpp_test_steps())
        lint_jobs.extend(_list_cpp_lint_steps())

    test_steps = "\n".join(
        "    " + step for step in test_jobs
    )

    lint_steps = "\n".join(
        "    " + step for step in lint_jobs
    )

    config = f"""# GitHub Actions CI configuration
# Generated by crb — CodeReviewerBot CI/CD template
# https://github.com/sunhatSH/CodeReviewerBot

name: CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
    tags: ["v*"]

env:
  PYTHON_VERSION: "3.13"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{{{ env.PYTHON_VERSION }}}}
{test_steps}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{lint_steps}

  check-branch-protection:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        env:
          HEAD_REF: ${{{{ github.head_ref }}}}
        run: |
          if [[ "$HEAD_REF" == "main" || "$HEAD_REF" == "master" ]]; then
            echo "::error::Direct commits to main/master branch are not allowed."
            exit 1
          fi
          echo "Branch '$HEAD_REF' is valid for PR."

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, lint]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
"""
    return config


def generate_gitlab_ci(
    project_root: str,
    languages: Optional[dict[str, bool]] = None,
) -> str:
    """Generate a GitLab CI configuration for the detected project.

    Args:
        project_root: Project root directory.
        languages: Pre-detected languages (None = auto-detect).

    Returns:
        GitLab CI YAML content.
    """
    if languages is None:
        languages = detect_project_languages(project_root)

    # Build lint script commands
    lint_cmds: list[str] = []
    test_cmds: list[str] = []

    if languages.get("python"):
        lint_cmds.extend([
            "ruff check src/",
            "mypy src/ --ignore-missing-imports",
        ])
        test_cmds.append("python -m pytest tests/ -v")
    if languages.get("go"):
        lint_cmds.extend([
            "golangci-lint run ./...",
            "go vet ./...",
        ])
        test_cmds.append("go test ./... -v -race")
    if languages.get("rust"):
        lint_cmds.extend([
            "cargo fmt --check",
            "cargo clippy -- -D warnings",
        ])
        test_cmds.append("cargo test --all-features")
    if languages.get("c_cpp"):
        lint_cmds.append("clang-tidy src/ --checks='*'")
        test_cmds.extend([
            "cmake -B build -DCMAKE_BUILD_TYPE=Debug",
            "cmake --build build",
            "ctest --test-dir build --output-on-failure",
        ])

    lint_script = "\n    - ".join(lint_cmds)
    test_script = "\n    - ".join(test_cmds)

    config = f"""# GitLab CI configuration
# Generated by crb — CodeReviewerBot CI/CD template

stages:
  - lint
  - test
  - release

lint:
  stage: lint
  script:{lint_script}
  only:
    - merge_requests
    - main
    - master

test:
  stage: test
  script:{test_script}
  only:
    - merge_requests
    - main
    - master

release:
  stage: release
  script:
    - echo "Creating release $CI_COMMIT_TAG..."
  only:
    - tags
  except:
    - branches
"""
    return config


def write_templates(
    project_root: str,
    output_dir: str | None = None,
) -> list[str]:
    """Generate and write CI/CD template files for a target project.

    Args:
        project_root: Project root directory to detect languages from.
        output_dir: Output directory (defaults to project_root).

    Returns:
        List of file paths written.
    """
    if output_dir is None:
        output_dir = project_root

    languages = detect_project_languages(project_root)
    written: list[str] = []

    # GitHub Actions
    gh_content = generate_github_actions(project_root, languages)
    gh_dir = Path(output_dir) / ".github" / "workflows"
    gh_dir.mkdir(parents=True, exist_ok=True)
    gh_path = gh_dir / "ci.yml"
    gh_path.write_text(gh_content)
    written.append(str(gh_path))

    # GitLab CI
    gl_content = generate_gitlab_ci(project_root, languages)
    gl_path = Path(output_dir) / ".gitlab-ci.yml"
    gl_path.write_text(gl_content)
    written.append(str(gl_path))

    return written


def generate_template_report(
    project_root: str,
    languages: Optional[dict[str, bool]] = None,
) -> str:
    """Generate a report describing which CI/CD templates are recommended.

    Args:
        project_root: Project root directory.
        languages: Pre-detected languages (None = auto-detect).

    Returns:
        Markdown report text.
    """
    if languages is None:
        languages = detect_project_languages(project_root)

    detected = [lang for lang, present in languages.items() if present]
    lines = [
        "## CI/CD 模板生成报告",
        "",
        f"### 检测到的语言",
        "",
    ]
    if detected:
        lines.extend(f"- {lang}" for lang in detected)
    else:
        lines.append("（未检测到已知源代码）")
    lines.extend([
        "",
        "### 已生成的模板",
        "",
        "- `.github/workflows/ci.yml` — GitHub Actions",
        "- `.gitlab-ci.yml` — GitLab CI",
        "",
        "### 配置说明",
        "",
        "1. 根据项目语言自动选择对应的检查工具",
        "2. 包含 PR 门禁（lint + test + 分支保护检查）",
        "3. 版本标签触发自动发布",
        "4. 如需定制，直接编辑生成的 YAML 文件",
        "",
    ])
    return "\n".join(lines)
